### ISSUE TITLE
messages have weird colors

### ISSUE THREAD

**Issue by MagdaN** [liqd/a4-product#186]
![bildschirmfoto 2017-12-07 um 21 57 12](https://user-images.githubusercontent.com/2905743/33738509-bdfa7dca-db99-11e7-8d32-aefd49f6f8ff.png)
![bildschirmfoto 2017-12-07 um 21 58 43](https://user-images.githubusercontent.com/2905743/33738555-d5c428d4-db99-11e7-8190-5af5e7232bbc.png)

**Comment by slomo** [comment]
Colors are also wired on my machine, but also the messages are ordered differently and are overlaped by content:

![selection_011](https://user-images.githubusercontent.com/141032/33765750-9a9881b6-dc1a-11e7-9d9b-029eefa16cb2.png)

**Comment by kleingeist** [comment]
i would split this to two issue.
the colors are autogenerated from the main colors. there had been a bug with the color definitions which was fixed in #174 i am not sure which colors had been used before. i think the default bootstrap ones.
but if the automatic policy does not work we can always overwrite them in `_variables.scss`
