### ISSUE TITLE
Tab bar breaks for widths smaller 609px

### ISSUE THREAD

**Issue by rittermo** [liqd/a4-product#204]
The tab bar of the particiaption page breaks for widths <= 609px. 

![bildschirmfoto 2017-12-12 um 09 44 07](https://user-images.githubusercontent.com/15341015/33875070-4764b58c-df21-11e7-9907-dd655f025976.png)

**Comment by kleingeist** [comment]
i think the same problem exists for meinBerlin, too but occurs only at a smaller width of 330px
not sure why the behavior is different as the css for the project detail page should be the same

![meinberlin-tab-breaking-330](https://user-images.githubusercontent.com/167407/33929457-dec599dc-dfe9-11e7-8257-c1f1e5a09360.png)

**Comment by kleingeist** [comment]
note that bootstrap has the same problem. but it occurs on larger widths because we have the follow buttons on the same line.
i'd propose to remove this from the milestone as it will be a bigger task to fix it

![bootstrap-tabs](https://user-images.githubusercontent.com/167407/33988866-0679f6ee-e0c6-11e7-80cc-f5d2cf1df88f.png)

**Comment by rittermo** [comment]
@kleingeist Thanks for the research. Since we only have three tabs, we have relatively stable conditions, so it is easy to fix (see screenshot).

<img width="506" alt="bildschirmfoto 2017-12-14 um 19 44 24" src="https://user-images.githubusercontent.com/15341015/34008932-49aa23d0-e107-11e7-9d06-d81f511af838.png">

In general: 
I have bit of a hard time to invest a US for small CSS fixes (which would be needed to matter if we use Bootstrap or some home-made solution) to something that was already part of a US in meinBerlin and now in Beteiligung.in. Bugfixing is part of a user story.

**Comment by rittermo** [comment]
Maybe make it a margin of 1.5 rem, so the buttons have room to breathe. And this of course needs to set for a breakpoint at/around 610px.

**Comment by fuzzylogic2000** [comment]
We didn't want to have a US for that. The issue is just a bit bigger than it seems at the first glance, because we also have tabs in other places (project detail on dashboard and in the container) and it would be good to fix that there as well.

I tried to fix it everywhere and also on mobile and not only tablet-size. I moved the buttons up, but also reduced the padding for smaller sizes. We still have to be careful, because only one or two more chars (or the translation to for example French) might break it again.
