### ISSUE TITLE
archived projects accessible via activity feed

### ISSUE THREAD

**Issue by CarolingerSeilchenspringer** [liqd/a4-product#758]
At https://www.beteiligung.in/liqd/ all projects are private but I can see the content of the projects if I click on the activity feed. Even if not signed in.

**Comment by rittermo** [comment]
Thank you for noticing, this @CarolingerSeilchenspringer ! @MagdaN Could we add this to the sprint as a task without US? I think it is a relatively critical issue.

**Comment by MagdaN** [comment]
sure

**Comment by rittermo** [comment]
Thank you! :)

**Comment by fuzzylogic2000** [comment]
Alright! We fixed the other new issues where we could see the content of private projects, when there was only one module and no event in that project. That was a new bug introduced with the timeline.
As for this issue here with the activitiy feed: all projects that are shown in the activitiy feed on bet.in/liqd are public, but archived. So, they are not shown as project tiles, but in the activity feed. Should we remove actions from archived projects from the activity feed?

**Comment by fuzzylogic2000** [comment]
currently archived projects can't be accessed anywhere (else) in a+?! #376

**Comment by fuzzylogic2000** [comment]
@rittermo Should activities of archived projects be removed from the activity list?? Otherwise we should close this issue!
